// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ramal.Data;

#nullable disable

namespace Ramal.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20230208145624_AddImpressoras")]
    partial class AddImpressoras
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ramal.Business.Models.Computador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Disco")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Memoria")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SistemaOperacional")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Computadores", (string)null);
                });

            modelBuilder.Entity("Ramal.Business.Models.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Caixa_Email", (string)null);
                });

            modelBuilder.Entity("Ramal.Business.Models.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ramal")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Funcionarios", (string)null);
                });

            modelBuilder.Entity("Ramal.Business.Models.Impressora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Tonner")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Impressoras", (string)null);
                });

            modelBuilder.Entity("Ramal.Business.Models.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Setores", (string)null);
                });

            modelBuilder.Entity("Ramal.Business.Models.Computador", b =>
                {
                    b.HasOne("Ramal.Business.Models.Setor", "Setor")
                        .WithMany("Computadores")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Ramal.Business.Models.Email", b =>
                {
                    b.HasOne("Ramal.Business.Models.Setor", "Setor")
                        .WithMany("Emails")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Ramal.Business.Models.Funcionario", b =>
                {
                    b.HasOne("Ramal.Business.Models.Setor", "Setor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Ramal.Business.Models.Impressora", b =>
                {
                    b.HasOne("Ramal.Business.Models.Setor", "Setor")
                        .WithMany("Impressoras")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Ramal.Business.Models.Setor", b =>
                {
                    b.Navigation("Computadores");

                    b.Navigation("Emails");

                    b.Navigation("Funcionarios");

                    b.Navigation("Impressoras");
                });
#pragma warning restore 612, 618
        }
    }
}
