// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ramal.Data;

#nullable disable

namespace Ramal.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20230124185314_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ramal.Business.Models.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ramal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Setor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Ramal.Business.Models.Funcionario", b =>
                {
                    b.HasOne("Ramal.Business.Models.Funcionario", null)
                        .WithMany("Favoritos")
                        .HasForeignKey("FuncionarioId");
                });

            modelBuilder.Entity("Ramal.Business.Models.Funcionario", b =>
                {
                    b.Navigation("Favoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
